
import java.awt.Graphics;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CLNTLAPI3
 */
public class bill extends javax.swing.JFrame {

    /**
     * Creates new form bill
     */
    public bill() {
        initComponents();
        fillCombo();
    }

    
    
     public void fillCombo()
    {
         try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111");
            Statement stmt;
            stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select distinct oid from order1");
            while(rs.next())
            {
                jc1.addItem(String.valueOf((rs.getInt(1))));
            }
            rs.close();
            stmt.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    }  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        odate = new javax.swing.JTextField();
        cid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gtotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jc1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        btable = new javax.swing.JTable();
        order = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Billing");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(210, 130, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1130, 710));
        setMinimumSize(new java.awt.Dimension(1130, 710));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1130, 710));
        jPanel2.setMinimumSize(new java.awt.Dimension(1130, 710));
        jPanel2.setPreferredSize(new java.awt.Dimension(1130, 710));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        odate.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jPanel2.add(odate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 190, 30));

        cid.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jPanel2.add(cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 190, 28));

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel4.setText("Order Date");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 90, 20));

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel2.setText("Customer Id");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 100, 28));

        gtotal.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        gtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gtotalActionPerformed(evt);
            }
        });
        jPanel2.add(gtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 130, 30));

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel5.setText("Total");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 60, 30));

        cname.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jPanel2.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 187, 29));

        jc1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc1ActionPerformed(evt);
            }
        });
        jPanel2.add(jc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 190, 27));

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel3.setText("Customer Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 29));

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setText("Select Order id");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 29));

        btable.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(btable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 510, 180));

        order.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        order.setText("Order");
        order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderActionPerformed(evt);
            }
        });
        jPanel2.add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 80, -1));

        jButton1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 80, -1));

        print.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel2.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 80, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();
home h=new home();
h.setSize(h.getSize());
h.show();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
public void display()
    {
    DefaultTableModel model=(DefaultTableModel) btable.getModel();
        model.setRowCount(0);
        int gt=0;
                try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111");
            Statement stmt;
            stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from order1 where oid='"+jc1.getSelectedItem()+"'");
            while(rs.next())
         {
             
             String name=rs.getString("pname");
             
             String price=rs.getString("price");
             String qty=rs.getString("qty");
             String total=rs.getString("total");
             //oqty=Integer.parseInt(qty);
             model.addRow(new Object[] {name,price,qty,total});
             gt=gt+Integer.parseInt(total);
             
            }
            gtotal.setText(String.valueOf(gt));
            rs.close();
            stmt.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    }
    
    
    
    
    }
    
    private void jc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc1ActionPerformed
        try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111");
            Statement stmt,stmt2;
            stmt=conn.createStatement();
            stmt2=conn.createStatement();

            ResultSet rs=stmt.executeQuery("select * from order1 where oid='"+jc1.getSelectedItem()+"'");
          //  ResultSet rs8=stmt2.executeQuery("select * from fees where studid='"+jc1.getSelectedItem()+"'");
          
            if(rs.next())
            {
                cid.setText((rs.getString(2)));
              
                odate.setText(rs.getString(3));
                 
                
            }
            stmt.close();
            ResultSet rs1=stmt2.executeQuery("select * from customer where cid='"+Integer.parseInt(cid.getText())+"'");
             if(rs1.next())
             {
                 cname.setText(rs1.getString(2));
             }
             
            stmt2.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    } 
        display();
        
    }//GEN-LAST:event_jc1ActionPerformed

    private void gtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtotalActionPerformed
        
    }//GEN-LAST:event_gtotalActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        Toolkit tkp=jPanel2.getToolkit();
        PrintJob pjp=tkp.getPrintJob(this, null, null);
        Graphics g=pjp.getGraphics();
        jPanel2.print(g);
        g.dispose();
        pjp.end();
    }//GEN-LAST:event_printActionPerformed

    private void orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderActionPerformed
dispose();
        order o=new order();
o.setSize(o.getSize());
o.show();// TODO add your handling code here:
    }//GEN-LAST:event_orderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable btable;
    private javax.swing.JTextField cid;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField gtotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jc1;
    private javax.swing.JTextField odate;
    private javax.swing.JButton order;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables
}
