
import java.sql.*;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Roshan Gatkal
 */
public class customer extends javax.swing.JFrame {
    static int inc;
    boolean ins=false;
    private Object JOptionpane;

    /**
     * Creates new form customer
     */
    public customer() {
        initComponents();
        //t1.setVisible(false);
        // fillCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        cname = new javax.swing.JTextField();
        ccno = new javax.swing.JTextField();
        cemail = new javax.swing.JTextField();
        caddr = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        display = new javax.swing.JButton();
        j7 = new javax.swing.JLabel();
        cl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(210, 130, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1130, 710));
        setMinimumSize(new java.awt.Dimension(1130, 710));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contact no");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        cid.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        getContentPane().add(cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 197, 40));

        cname.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cnameKeyPressed(evt);
            }
        });
        getContentPane().add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 197, 40));

        ccno.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ccno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ccnoKeyPressed(evt);
            }
        });
        getContentPane().add(ccno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 197, 40));

        cemail.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        getContentPane().add(cemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 197, 40));

        caddr.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        getContentPane().add(caddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 197, 40));

        add.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 90, 25));

        save.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 90, 25));

        clear.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 90, 25));

        exit.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 90, 25));

        home.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 90, 25));

        t1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Name", "Contact no.", "Email", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(t1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 610, 320));

        display.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        display.setText("Display");
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 90, 25));

        j7.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        j7.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(j7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 200, 20));
        getContentPane().add(cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 190, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentbackground.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setMaximumSize(new java.awt.Dimension(1130, 710));
        jLabel6.setMinimumSize(new java.awt.Dimension(1130, 710));
        jLabel6.setPreferredSize(new java.awt.Dimension(1130, 710));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
try
{
    Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111");
Statement stmt;
stmt=con.createStatement();
ResultSet rs=stmt.executeQuery("select * from customer");
while(rs.next())
{
    inc=rs.getInt(1);
    
}
    rs.close();
    stmt.close();
    con.close();    
}

catch(Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
}
inc++;
cid.setText(String.valueOf(inc));
cid.setEditable(false);
cname.setText("");
ccno.setText("");
cemail.setText("");
caddr.setText("");

ins=true;

    }//GEN-LAST:event_addActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
if(ins=true)
{
        try
{
    Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111"); 
PreparedStatement stmt1;

if(cname.getText().isEmpty() || ccno.getText().isEmpty() || cemail.getText().isEmpty() || caddr.getText().isEmpty())
{
    JOptionPane.showMessageDialog(null, "One or more textfield empty!!!!");  
}  
else
{


stmt1=con.prepareStatement("insert into customer values(?,?,?,?,?)");
stmt1.setInt(1,(Integer.parseInt(cid.getText())));
stmt1.setString(2,cname.getText());
stmt1.setString(3,ccno.getText());
stmt1.setString(4,cemail.getText());
stmt1.setString(5,caddr.getText());

stmt1.executeUpdate();
JOptionPane.showMessageDialog(null,"Customer added succesfully");
stmt1.close();
}
//if(cname.equals(""))//Validation
//{
  //  JOptionPane.showMessageDialog(null,"Please enter name");
//}
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null, e.getMessage());
    /*if(cname.equals(""))
    {
        JOptionPane.showMessageDialog(null,"Please Enter Name");
        
    }*/
    
}
}
else
    JOptionPane.showMessageDialog(null,"Please Click on add button");

    
// TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed
/*public void fillCombo()
    {
         try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111");
            Statement stmt;
            stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from customer");
            while(rs.next())
            {
                jc1.addItem((rs.getString(2)));
            }
            rs.close();
            stmt.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    } 
    }
    
    */ 
    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
       dispose();
       home h=new home();
h.setSize(h.getSize());
h.show();

    }//GEN-LAST:event_homeActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
DefaultTableModel model=(DefaultTableModel) t1.getModel();
        model.setRowCount(0);
 try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111");
            Statement stmt;
            stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from customer ");
            while(rs.next())
         {
             String id=rs.getString("cid");
             String name=rs.getString("cname");
             String contact=rs.getString("ccno");
             String email=rs.getString("cemail");
             String addr=rs.getString("caddr");
             
             model.addRow(new Object[] {id,name,contact,email,addr});
            }
            rs.close();
            stmt.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    }
        


// TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
  cid.setText("");
 cname.setText("");
ccno.setText("");
cemail.setText("");
caddr.setText("");       
// TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
dispose();
login l=new login();
l.setSize(l.getSize());
l.show();
        
// TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void ccnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ccnoKeyPressed
try
{
int i=Integer.parseInt(ccno.getText());
j7.setText("");
}catch(NumberFormatException e)
{
j7.setText("Invalid Number");
}// TODO add your handling code here:
    }//GEN-LAST:event_ccnoKeyPressed

    private void cnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyPressed
char c=evt.getKeyChar();
if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c))
    cname.setEditable(true);
else
    cname.setEditable(false);
    }//GEN-LAST:event_cnameKeyPressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField caddr;
    private javax.swing.JTextField ccno;
    private javax.swing.JTextField cemail;
    private javax.swing.JTextField cid;
    private javax.swing.JLabel cl;
    private javax.swing.JButton clear;
    private javax.swing.JTextField cname;
    private javax.swing.JButton display;
    private javax.swing.JButton exit;
    private javax.swing.JButton home;
    private javax.swing.JLabel j7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton save;
    private javax.swing.JTable t1;
    // End of variables declaration//GEN-END:variables
}
