
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import static javax.management.Query.gt;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Roshan Gatkal
 */
public class order extends javax.swing.JFrame {

   // int oqty;
    //String q;
    static int inc;
    boolean ins=false;
    /**
     * Creates new form order
     */
    public order() {
        initComponents();
        display();
        display1();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        t2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        t3 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        oid = new javax.swing.JTextField();
        dc = new datechooser.beans.DateChooserCombo();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        bill = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order");
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        t1.setForeground(new java.awt.Color(204, 0, 0));
        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Contact No", "Email", "Address"
            }
        ));
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 202));

        t2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        t2.setForeground(new java.awt.Color(204, 0, 0));
        t2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Type", "Price", "Quantity"
            }
        ));
        t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(t2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 260));

        t3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        t3.setForeground(new java.awt.Color(204, 0, 0));
        t3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t3MouseClicked(evt);
            }
        });
        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t3KeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(t3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 538, 260));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Order id");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 92, -1, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("Order Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 129, -1, -1));

        cid.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        cid.setForeground(new java.awt.Color(204, 0, 0));
        cid.setName(""); // NOI18N
        getContentPane().add(cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 49, 216, -1));

        oid.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        oid.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(oid, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 89, 216, -1));

        dc.setCalendarBackground(new java.awt.Color(204, 0, 51));
        dc.setFormat(2);
        dc.setFieldFont(new java.awt.Font("Times New Roman", java.awt.Font.PLAIN, 20));
        dc.setLocale(new java.util.Locale("en", "IN", ""));
        dc.setLocked(true);
        getContentPane().add(dc, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 129, 216, 30));

        jButton1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 100, -1));

        jButton3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("Insert Order");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, -1, -1));

        jButton2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 90, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("Customer id");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, -1, -1));

        bill.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        bill.setForeground(new java.awt.Color(204, 0, 0));
        bill.setText("Bill");
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });
        getContentPane().add(bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 250, 120, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Order");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 200, -1));

        jButton4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 0, 0));
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, 100, 30));

        jButton5.setText("Refresh Product");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try
{
    Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111");
Statement stmt;
stmt=con.createStatement();
ResultSet rs=stmt.executeQuery("select * from order1");
while(rs.next())
{
    inc=rs.getInt(1);
    
}
    rs.close();
    stmt.close();
    con.close();    
}
catch(Exception e){
//JOptionPane.showMessageDialog(null, e.getMessage());
}
inc++;
oid.setText(String.valueOf(inc));
oid.setEditable(false);
ins=true;        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MouseClicked
    TableModel model1=t2.getModel();
    int indexs []=t2.getSelectedRows();
    Object [] row =new Object[5];
    int rqty;
    DefaultTableModel model2=(DefaultTableModel)t3.getModel();
    
    for(int i=0;i<indexs.length;i++)
        
    {
        row[0]=model1.getValueAt(indexs[i], 0);
        row[1]=model1.getValueAt(indexs[i], 1);
        row[3]=model1.getValueAt(indexs[i], 3);
        row[4]=model1.getValueAt(indexs[i], 4);
         String q=JOptionPane.showInputDialog(null, "Enter Qty");
        int oqty=Integer.parseInt(model1.getValueAt(indexs[i],4).toString());
        row[4]=q;
        
        int qty=Integer.parseInt(q);
        int price=Integer.parseInt(model1.getValueAt(indexs[i],3).toString());
        int total=qty*price;
        //row[4]=total;
        if(oqty>0&&qty<oqty)
        {
             rqty=oqty-qty;
             model1.setValueAt(rqty, indexs[i],4 );
             model2.addRow(new Object[]{row[0],row[1],row[3],row[4],total});
        } 
        else
           JOptionPane.showMessageDialog(null, "Qty not available");
            
       // model2.addRow(new Object[]{row[0],row[1],row[3],row[4],total});
        //model2.addRow(row);
        
        
    }
    
   
  
      //  UpdateProduct();
// TODO add your handling code here:
    }//GEN-LAST:event_t2MouseClicked
void UpdateProduct()
{
    try{
 TableModel model1=t2.getModel();
 
int rows=t2.getRowCount();
Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111");
PreparedStatement stmt1,st2;

 for(int row=0;row<rows;row++)
{
    
    int id=Integer.parseInt(t2.getValueAt(row, 0).toString());
    
    String name=(String)t2.getValueAt(row, 1);
    String type=(String)t2.getValueAt(row,2);
    int price=Integer.parseInt(t2.getValueAt(row, 3).toString());
    int qty=Integer.parseInt(t2.getValueAt(row, 4).toString());
     stmt1=con.prepareStatement("update product set pname=?,ptype=?,pprice=?,pqty=? where product.pid='"+id+"'");    
stmt1.setString(1, name);
    stmt1.setString(2, type);
    stmt1.setInt(3, price);
    stmt1.setInt(4,qty);
    stmt1.executeUpdate();
}

}
catch(Exception e){
    JOptionPane.showMessageDialog(this,e.getMessage());
}
}
    private void t1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseClicked
     TableModel model1=t1.getModel();
    int indexs []=t1.getSelectedRows();
    Object [] row =new Object[4];
    
    DefaultTableModel model2=(DefaultTableModel)t3.getModel();
    
    for(int i=0;i<indexs.length;i++)
        
    {
        cid.setText(String.valueOf(model1.getValueAt(indexs[i], 0)));
       
        
      
        
    } 
        

// TODO add your handling code here:
    }//GEN-LAST:event_t1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();
home h=new home();
h.setSize(h.getSize());
h.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int oqty;
if(ins=true)
{
        try
{
    Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111"); 
//con.setAutoCommit(false);
PreparedStatement stmt1,st2;

int orderid =Integer.parseInt(oid.getText());
int custid=Integer.parseInt(cid.getText());
//int qty=Integer.parseInt(tqty.getText());
String dt=dc.getText();
int rows=t3.getRowCount();
for(int row=0;row<rows;row++)
{
    int pid=Integer.parseInt(t3.getValueAt(row, 0).toString());
    String name=(String)t3.getValueAt(row, 1);
    int price=Integer.parseInt(t3.getValueAt(row, 2).toString());
    int qty=Integer.parseInt(t3.getValueAt(row, 3).toString());
    int total=Integer.parseInt(t3.getValueAt(row, 4).toString());
//    int rqty=oqty-Integer.parseInt(q);
   stmt1=con.prepareStatement("insert into order1 values(?,?,?,?,?,?,?,?)"); 
    stmt1.setInt(1, orderid);
    stmt1.setInt(2, custid);
    stmt1.setString(3, dt);
    stmt1.setInt(4,pid);
    stmt1.setString(5, name);
    stmt1.setInt(6,price);
    stmt1.setInt(7,qty);
    stmt1.setInt(8,total);
  //    stmt1=conn.prepareStatement("update customer set cid=?,ccno=?,cemail=?,caddr=? where customer.cname='"+jc1.getSelectedItem()+"'");
   // st2=con.prepareStatement("update product set pqty=? where product.pid='"+pid+"'");
    //st2.setInt(1,rqty);
    //st2.executeUpdate();
    //refresh();
    stmt1.executeUpdate();
}


//con.commit();
JOptionPane.showMessageDialog(null, "Saved");

}
catch(Exception e){
JOptionPane.showMessageDialog(null, e.getMessage());
}

 UpdateProduct();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    
    }
    private void t3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t3MouseClicked
  // JTable from;
//        DefaultTableModel tm=(DefaultTableModel) t3.getModel();
//       int[] rows=t3.getSelectedRows();
//       for(int row:rows)
//       {
//       
//           tm.removeRow(t3.convertRowIndexToModel(row));
//       }
//       t3.clearSelection();
    }//GEN-LAST:event_t3MouseClicked

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
dispose();
bill o=new bill();
o.setSize(o.getSize());
o.show();
// TODO add your handling code here:
    }//GEN-LAST:event_billActionPerformed

    private void t3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyPressed
   TableModel model1=t3.getModel();
    int indexs []=t3.getSelectedRows();
    Object [] row =new Object[5];
    int rqty;
    DefaultTableModel model2=(DefaultTableModel)t3.getModel();
    
    for(int i=0;i<indexs.length;i++)
        
    {
        row[0]=model1.getValueAt(indexs[i], 0);
        row[1]=model1.getValueAt(indexs[i], 1);
        row[3]=model1.getValueAt(indexs[i], 2);
        //row[4]=model1.getValueAt(indexs[i], 4);
        // String q=JOptionPane.showInputDialog(null, "Enter Qty");
//        int oqty=Integer.parseInt(model1.getValueAt(indexs[i],4).toString());
//        row[4]=q;
        
        int qty=Integer.parseInt(model1.getValueAt(indexs[i],2).toString());
        int price=Integer.parseInt(model1.getValueAt(indexs[i],3).toString());
        int total=qty*price;
        //row[4]=total;
//        if(oqty>0&&qty<oqty)
//        {
//             rqty=oqty-qty;
             model1.setValueAt(total, indexs[i],4 );
            // model2.addRow(new Object[]{row[0],row[1],row[3],row[4],total});
//        } 
//        else
//           JOptionPane.showMessageDialog(null, "Qty not available");
            
       // model2.addRow(new Object[]{row[0],row[1],row[3],row[4],total});
        //model2.addRow(row);
        
        
    }
          // TODO add your handling code here:
    }//GEN-LAST:event_t3KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  DefaultTableModel tm=(DefaultTableModel) t3.getModel();
       int[] rows=t3.getSelectedRows();
       for(int row:rows)
       {
       
           tm.removeRow(t3.convertRowIndexToModel(row));
       }
       t3.clearSelection(); 
       
dispose();
order o1=new order();
o1.setSize(o1.getSize());
o1.show();



// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
dispose();
order o1=new order();
o1.setSize(o1.getSize());
o1.show();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
    
    
    
    public void display()
    {
    DefaultTableModel model=(DefaultTableModel) t1.getModel();
        model.setRowCount(0);
 try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111");
            Statement stmt;
            stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from customer ");
            while(rs.next())
         {
             String id=rs.getString("cid");
             String name=rs.getString("cname");
             String contact=rs.getString("ccno");
             String email=rs.getString("cemail");
             String addr=rs.getString("caddr");
             
             model.addRow(new Object[] {id,name,contact,email,addr});
            }
            rs.close();
            stmt.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    }
    
    
    
    
    }
    
    public void display1()
    {
    DefaultTableModel model=(DefaultTableModel) t2.getModel();
        model.setRowCount(0);
 try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111");
            Statement stmt;
            stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from product ");
            while(rs.next())
         {
             String id=rs.getString("pid");
             String name=rs.getString("pname");
             String type=rs.getString("ptype");
             String price=rs.getString("pprice");
             String qty=rs.getString("pqty");
             //oqty=Integer.parseInt(qty);
             model.addRow(new Object[] {id,name,type,price,qty});
            }
            rs.close();
            stmt.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    }
    
    
    
    
    }
    
   void refresh()
   {
       DefaultTableModel model=(DefaultTableModel) t2.getModel();
       while(model.getRowCount()>0)
       {
           model.setRowCount(0);
       }
       //  DefaultTableModel model=(DefaultTableModel) t2.getModel();
        model.setRowCount(0);
 try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111");
            Statement stmt;
            stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from product ");
            while(rs.next())
         {
             String id=rs.getString("pid");
             String name=rs.getString("pname");
             //String type=rs.getString("ptype");
             String price=rs.getString("pprice");
             String qty=rs.getString("pqty");
           //  oqty=Integer.parseInt(qty);
             model.addRow(new Object[] {id,name,price,qty});
            }
            rs.close();
            stmt.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    }
   }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bill;
    private javax.swing.JTextField cid;
    private datechooser.beans.DateChooserCombo dc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField oid;
    private javax.swing.JTable t1;
    private javax.swing.JTable t2;
    private javax.swing.JTable t3;
    // End of variables declaration//GEN-END:variables
}
