
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CLNTLAPI3
 */
public class r_ord extends javax.swing.JFrame {

    /**
     * Creates new form r_ord
     */
    public r_ord() {
        initComponents();
        fillCombo();
        fillproduct();
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        btable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jc1 = new javax.swing.JComboBox();
        jc2 = new javax.swing.JComboBox();
        jc3 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jc4 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order Report");
        setBounds(new java.awt.Rectangle(210, 130, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btable.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Product", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(btable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 68, 740, 201));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 326, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Show");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 326, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Print");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 326, -1, -1));

        jc1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc1ActionPerformed(evt);
            }
        });
        getContentPane().add(jc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 180, -1));

        jc2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        getContentPane().add(jc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 230, -1));

        jc3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        getContentPane().add(jc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 230, -1));

        jButton4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jButton4.setText("Show Report ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 190, -1, -1));

        jc4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc4ActionPerformed(evt);
            }
        });
        getContentPane().add(jc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 320, 230, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel1.setText("Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 70, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel2.setText("Start Date");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel3.setText("End Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel4.setText("Show Report Between Dates");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 180, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel5.setText("Productwise Report");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, 140, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel6.setText("Select Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel7.setText("Datewise Report");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 180, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jLabel8.setText("Order Report");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 250, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();
home h=new home();
h.setSize(h.getSize());
h.show();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void fillCombo()
    {
         try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111");
            Statement stmt,stmt1;
            stmt=conn.createStatement();
//            stmt1=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from order1");
//             ResultSet rs5=stmt1.executeQuery("select * from product");
//             while(rs5.next())
//             {
//              jc4.addItem((rs.getString(2)));
//             }
//             rs5.close();
//             stmt1.close();
            while(rs.next())
            {
                jc1.addItem((rs.getString(3)));
                jc2.addItem((rs.getString(3)));
                        jc3.addItem((rs.getString(3)));
                       
            }
            rs.close();
           // rs1.close();
            stmt.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    }  
    }
    
    
    public void fillproduct()
    {
         try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111");
            Statement stmt;
            stmt=conn.createStatement();
//            stmt1=conn.createStatement();
//            ResultSet rs=stmt.executeQuery("select * from order1");
             ResultSet rs=stmt.executeQuery("select * from order1");
             while(rs.next())
             {
              jc4.addItem((rs.getString(5)));
             }
             rs.close();
             stmt.close();
            
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    }  
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    public void display()
    {
    DefaultTableModel model=(DefaultTableModel) btable.getModel();
        model.setRowCount(0);
        int gt=0;
                try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111");
            Statement stmt;
            stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from order1 where oid='"+jc1.getSelectedItem()+"'");
            while(rs.next())
         {
             
             String name=rs.getString("pname");
             
             String price=rs.getString("price");
             String qty=rs.getString("qty");
             String total=rs.getString("total");
             //oqty=Integer.parseInt(qty);
             model.addRow(new Object[] {name,price,qty,total});
             gt=gt+Integer.parseInt(total);
             
            }
            //gtotal.setText(String.valueOf(gt));
            rs.close();
            stmt.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    }
    
    
    
    
    }
    
    
    
    
    
    
    
    
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 {
    DefaultTableModel model=(DefaultTableModel) btable.getModel();
        model.setRowCount(0);
        int gt=0;
                try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111");
            Statement stmt,stmt1;
            stmt=conn.createStatement();
            stmt1=conn.createStatement();
            ResultSet rs1,rs2;
            rs1=stmt.executeQuery("select * from order1");
           
            
           /*  if(rs2.next())
             {
                // cname.setText(rs1.getString(2));
                 String name=rs2.getString("name");
             }*/
            String name;
            while(rs1.next())
         {
             String cid=rs1.getString("cid");
            
             String id=rs1.getString("oid");
             String product=rs1.getString("pname");
             rs2=stmt1.executeQuery("select distinct cname from customer where cid='"+cid+"'");
            
             String price=rs1.getString("price");
             String qty=rs1.getString("qty");
             String total=rs1.getString("total");
             //oqty=Integer.parseInt(qty);
              gt=gt+Integer.parseInt(total);
              if(rs2.next())
             {   
                 name=rs2.getString("cname");
                model.addRow(new Object[] {id,name,product,price,qty,total});

             }
                         
             
            }
          //  gtotal.setText(String.valueOf(gt));
            rs1.close();
            //rs2.close();
            stmt.close();
            //stmt1.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    }
 }       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc1ActionPerformed
 DefaultTableModel model=(DefaultTableModel) btable.getModel();
        model.setRowCount(0);
        int gt=0;
                try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111");
            Statement stmt,stmt1;
            stmt=conn.createStatement();
            stmt1=conn.createStatement();
            ResultSet rs1,rs2;
            rs1=stmt.executeQuery("select * from order1 where date='"+jc1.getSelectedItem()+"'");
           
            
           /*  if(rs2.next())
             {
                // cname.setText(rs1.getString(2));
                 String name=rs2.getString("name");
             }*/
            String name;
            while(rs1.next())
         {
             String cid=rs1.getString("cid");
            
             String id=rs1.getString("oid");
             String product=rs1.getString("pname");
             rs2=stmt1.executeQuery("select distinct cname from customer where cid='"+cid+"'");
            
             String price=rs1.getString("price");
             String qty=rs1.getString("qty");
             String total=rs1.getString("total");
             //oqty=Integer.parseInt(qty);
              gt=gt+Integer.parseInt(total);
              if(rs2.next())
             {   
                 name=rs2.getString("cname");
                model.addRow(new Object[] {id,name,product,price,qty,total});

             }
                         
             
            }
          //  gtotal.setText(String.valueOf(gt));
            rs1.close();
            //rs2.close();
            stmt.close();
            //stmt1.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    }     
    }//GEN-LAST:event_jc1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 DefaultTableModel model=(DefaultTableModel) btable.getModel();
        model.setRowCount(0);
        int gt=0;
                try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111");
            Statement stmt,stmt1;
            stmt=conn.createStatement();
            stmt1=conn.createStatement();
            ResultSet rs1,rs2;
            rs1=stmt.executeQuery("select * from order1 where date<'"+jc1.getSelectedItem()+"'&& date>'"+jc1.getSelectedItem()+"'");
           
            
           /*  if(rs2.next())
             {
                // cname.setText(rs1.getString(2));
                 String name=rs2.getString("name");
             }*/
            String name;
            while(rs1.next())
         {
             String cid=rs1.getString("cid");
            
             String id=rs1.getString("oid");
             String product=rs1.getString("pname");
             rs2=stmt1.executeQuery("select distinct cname from customer where cid='"+cid+"'");
            
             String price=rs1.getString("price");
             String qty=rs1.getString("qty");
             String total=rs1.getString("total");
             //oqty=Integer.parseInt(qty);
              gt=gt+Integer.parseInt(total);
              if(rs2.next())
             {   
                 name=rs2.getString("cname");
                model.addRow(new Object[] {id,name,product,price,qty,total});

             }
                         
             
            }
          //  gtotal.setText(String.valueOf(gt));
            rs1.close();
            //rs2.close();
            stmt.close();
            //stmt1.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    }     
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc4ActionPerformed
DefaultTableModel model=(DefaultTableModel) btable.getModel();
        model.setRowCount(0);
        int gt=0;
                try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","1111");
            Statement stmt,stmt1;
            stmt=conn.createStatement();
            stmt1=conn.createStatement();
            ResultSet rs1,rs2;
            rs1=stmt.executeQuery("select * from order1 where pname='"+jc4.getSelectedItem()+"'");
           
            
           /*  if(rs2.next())
             {
                // cname.setText(rs1.getString(2));
                 String name=rs2.getString("name");
             }*/
            String name;
            while(rs1.next())
         {
             String cid=rs1.getString("cid");
            
             String id=rs1.getString("oid");
             String product=rs1.getString("pname");
             rs2=stmt1.executeQuery("select distinct cname from customer where cid='"+cid+"'");
            
             String price=rs1.getString("price");
             String qty=rs1.getString("qty");
             String total=rs1.getString("total");
             //oqty=Integer.parseInt(qty);
              gt=gt+Integer.parseInt(total);
              if(rs2.next())
             {   
                 name=rs2.getString("cname");
                model.addRow(new Object[] {id,name,product,price,qty,total});

             }
                         
             
            }
          //  gtotal.setText(String.valueOf(gt));
            rs1.close();
            //rs2.close();
            stmt.close();
            //stmt1.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
    }             // TODO add your handling code here:
    }//GEN-LAST:event_jc4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(r_ord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(r_ord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(r_ord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(r_ord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new r_ord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable btable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jc1;
    private javax.swing.JComboBox jc2;
    private javax.swing.JComboBox jc3;
    private javax.swing.JComboBox jc4;
    // End of variables declaration//GEN-END:variables
}
